### ISSUE TITLE
[Win10] Agent installation doesn't work

### ISSUE THREAD

**Issue by trololo2305** [Privatix/privatix#181]
![2019-06-21_1305](https://user-images.githubusercontent.com/40266734/59915438-53ac1c80-9425-11e9-8713-ac564645b778.png)

log https://drive.google.com/file/d/1jnUM3zCg8R58K3nxffh8VIboDxgbmvV1/view?usp=sharing

For more details please contact to @spekter

**Comment by devalexandr** [comment]
in this issue Agent was not properly uninstalled and now it can't be installed due to error

**Comment by devalexandr** [comment]
+ error indicated incorrectly
2019/06/19 21:50:01 WARNING failed to execute 'install tap'

**Comment by sofabeat** [comment]
It seems that `set-nat.ps1` script is executed with wrong TAP adapter PnPDeviceID (TAPdeviceAddress argument). PowerShell command: `Get-NetAdapter | ? {$_.InterfaceDescription -match "TAP-"} | select ifIndex, name, PnPDeviceID` may show that several TAP adapter exists and script was executed with `TAPdeviceAddress` that corresponds to another TAP adapter.
One such case may be seen https://privatix.slack.com/archives/CCN7CEF7C/p1564439059075700
Installation was fixed by manually setting Internet Connection Sharing via GUI, while choosing correct adapter.

**Comment by trololo2305** [comment]
Can't reproduce
