### ISSUE TITLE
Eth balance not updating

### ISSUE THREAD

**Issue by achillelrc** [Privatix/privatix#23]
Hi,
I wanna get a try and [I successfully sent 2$](https://etherscan.io/address/0xd9c10c76c31ff10e86c21517cdbdeaf6fda8b091) to the ethereum wallet you created for me but I can't see the changes on the gui :/

![image of the gui](https://i.imgur.com/fgZVoNZ.png)

My os is Ubuntu.

I have another question if I want to send the money made as an agent I can I do that  from the gui?

Thanks for your help

Achille

**Comment by drew2a** [comment]
Hi!

It is because we launched on testnet only (rinkeby)

To get ETH and PRIX, you need to use telegram bot: https://t.me/PRIXBot

> I have another question if I want to send the money made as an agent I can I do that from the gui?

There are two options, inside GUI:
1. Transfer PRIX from Privatix Service Contract to Privatix Token Contract
2. Transfer PRIX from Privatix Token Contract to Privatix Service Contract.

To send PRIX to another address, you have to use a wallet (metamask, for example)

**Comment by achillelrc** [comment]
Thank you!
